### ISSUE TITLE
Can't complete the pull-request because Travis-CI fails

### ISSUE THREAD

**Issue by mnofresno** [flot/flot#1558]
Hi, i made a very little undefined reference fix to the jquery.flot.pie.js in my fork: mnofresno/flot but can't complete the pull request because Travis integration tests fails on another point of the code.

This is the error:
```javascript
npm ERR! Error: No compatible version found: minimatch@'^3.0.4'
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
The command "eval npm install  " failed. Retrying, 2 of 3.
```

Can we by pass that check to merge? or can we repair this Travis-CI testing?

**Comment by nschonni** [comment]
Yup, the `0.9-work` branch is the cleaned up vNext, but there hasn't been much traction with getting it released for awhile. Sorry ☹️
